### ISSUE TITLE
Cannot use if condition inside a validator's functor

### ISSUE THREAD

**Issue by tiendatiowa** [wix/accord#74] opened 2016-07-07 08:21 UTC
Here is an example code:

```scala
  def testValidator(max: Double): TransformedValidator[Double] = validator[Double] { value =>
    if (max > 0.0) {
      value as "Value must be less than or equal to max" must be <= max
    }
    ()
  }
```

Unit test:

```scala
    "Test validator" - {
      "Should pass" in {
        val validateResult = accord.validate(10.0)(AccordValidator.testValidator(-1.0))
        validateResult.isSuccess shouldBe true
      }
    }
```

The unit test should pass, but it actually fails.

**Comment by holograph** [comment] 2016-07-07 12:39
Hi @tiendatiowa, and thanks for trying out Accord!

First things first: `if`s are only supported as of 0.6 (due later this week, as soon as I wrap up the documentation). You can check it out via the snapshot builds, and I've verified that it works as expected:

```scala
scala> import com.wix.accord.dsl._
import com.wix.accord.dsl._

scala> def testValidator(max: Double) = validator[Double] { value => if (max > 0.0) value as "Value must be less than or equal to max" must be <= max }
testValidator: (max: Double)com.wix.accord.transform.ValidationTransform.TransformedValidator[Double]

scala> import com.wix.accord
import com.wix.accord

scala> val validateResult = accord.validate(10.0)(testValidator(-1.0))
validateResult: com.wix.accord.Result = Success
```

A few other pointers:

1. `TransformedValidator` is an implementation detail and you usually don't have to specify it explicitly;
2. Instead of `.isSuccess shouldBe true` you can use the `ResultMatchers` suitable to your testing library, and just go with `validateResult should succeed` or `validateResult shouldBe aSuccess`, depending on your particular library flavour;
3. You really don't need that extra unit marker (`()`) on the validator definition.

I'm marking this as a duplicate of #58 for now, would love your feedback on whether or not 0.6 works for you!

**Closed by holograph** 2016-07-07 12:39 UTC
Labels: duplicate

**Comment by tiendatiowa** [comment] 2016-07-07 15:31
Thanks for the quick reply, @holograph. I'll update our accord library to 0.6 as soon as possible and let you know if the issue is still there :)
