### ISSUE TITLE
Scala.js support

### ISSUE THREAD

**Issue by antonkulaga** [wix/accord#19] opened 2014-04-10 18:27 UTC
As validation is a common task for the frontend it will be be great to see scalajs support in accord.

**Comment by ngbinh** [comment] 2015-06-02 10:46
Just wondering if there is any progress on this issue? Thanks

**Comment by antonkulaga** [comment] 2015-06-04 07:45
Not from my side. I simply had not time for it (too many other libs to port to scalajs on my list) But there are also some good news: scalatest supports ScalaJS in its latest snapshot, that means that there is no need to rewrite the test

**Comment by holograph** [comment] 2015-07-13 22:00
This is basically pending ScalaTest support for Scala.js (I've no intention of rewriting all tests on another framework, but if someone wants to take a stab at it...)

**Comment by antonkulaga** [comment] 2015-07-13 23:01
ScalaTest 3.0.0-M7 works fine with ScalaJS, you an simply switch the project to it

**Comment by holograph** [comment] 2015-07-14 09:14
Indeed! I've started playing around with Scala.js, notwithstanding @antonkulaga's earlier experiments (the sbt plugin has come a long way since then). Right now I've run into a [silly issue](https://groups.google.com/forum/#!topic/scala-js/RJ8V_thUaQA) with the build, but you can see the result on the [scalajs-support branch](https://github.com/wix/accord/tree/scalajs-support).

**Comment by holograph** [comment] 2015-07-14 15:15
Almost works! It builds, but tests for `core` fail with an odd error message:

```
[error] Referring to non-existent class s_reflect_runtime_package$
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply$mcV$sp__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__O
[error]   called from Lorg_scalajs_testinterface_internal_Slave.org$scalajs$testinterface$internal$Slave$$jsonArg$1__F0__sjs_js_Dynamic
[error]   called from Lorg_scalajs_testinterface_internal_Slave.handleMsgImpl__T__F0__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.handleMsg__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$anonfun$1__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$js$exported$meth$init__O
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4
[error]   Lorg_scalajs_testinterface_internal_Slave
[error]   Lorg_scalajs_testinterface_internal_Master
[error] Referring to non-existent class s_tools_reflect_package$
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply$mcV$sp__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__O
[error]   called from Lorg_scalajs_testinterface_internal_Slave.org$scalajs$testinterface$internal$Slave$$jsonArg$1__F0__sjs_js_Dynamic
[error]   called from Lorg_scalajs_testinterface_internal_Slave.handleMsgImpl__T__F0__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.handleMsg__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$anonfun$1__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$js$exported$meth$init__O
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4
[error]   Lorg_scalajs_testinterface_internal_Slave
[error]   Lorg_scalajs_testinterface_internal_Master
[error] Referring to non-existent class s_tools_reflect_ToolBoxError
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply$mcV$sp__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__O
[error]   called from Lorg_scalajs_testinterface_internal_Slave.org$scalajs$testinterface$internal$Slave$$jsonArg$1__F0__sjs_js_Dynamic
[error]   called from Lorg_scalajs_testinterface_internal_Slave.handleMsgImpl__T__F0__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.handleMsg__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$anonfun$1__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$js$exported$meth$init__O
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4
[error]   Lorg_scalajs_testinterface_internal_Slave
[error]   Lorg_scalajs_testinterface_internal_Master
[error] Referring to non-existent class s_tools_reflect_ToolBoxError
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply$mcV$sp__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__O
[error]   called from Lorg_scalajs_testinterface_internal_Slave.org$scalajs$testinterface$internal$Slave$$jsonArg$1__F0__sjs_js_Dynamic
[error]   called from Lorg_scalajs_testinterface_internal_Slave.handleMsgImpl__T__F0__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.handleMsg__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$anonfun$1__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$js$exported$meth$init__O
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4
[error]   Lorg_scalajs_testinterface_internal_Slave
[error]   Lorg_scalajs_testinterface_internal_Master
[error] Referring to non-existent method s_tools_reflect_package$.ToolBox__s_reflect_api_JavaUniverse$JavaMirror__s_tools_reflect_ToolBoxFactory
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply$mcV$sp__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__O
[error]   called from Lorg_scalajs_testinterface_internal_Slave.org$scalajs$testinterface$internal$Slave$$jsonArg$1__F0__sjs_js_Dynamic
[error]   called from Lorg_scalajs_testinterface_internal_Slave.handleMsgImpl__T__F0__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.handleMsg__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$anonfun$1__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$js$exported$meth$init__O
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4
[error]   Lorg_scalajs_testinterface_internal_Slave
[error]   Lorg_scalajs_testinterface_internal_Master
[error] Referring to non-existent method jl_Class.getClassLoader__jl_ClassLoader
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply$mcV$sp__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__O
[error]   called from Lorg_scalajs_testinterface_internal_Slave.org$scalajs$testinterface$internal$Slave$$jsonArg$1__F0__sjs_js_Dynamic
[error]   called from Lorg_scalajs_testinterface_internal_Slave.handleMsgImpl__T__F0__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.handleMsg__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$anonfun$1__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$js$exported$meth$init__O
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4
[error]   Lorg_scalajs_testinterface_internal_Slave
[error]   Lorg_scalajs_testinterface_internal_Master
[error] Referring to non-existent method s_reflect_runtime_package$.universe__s_reflect_api_JavaUniverse
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply$mcV$sp__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__V
[error]   called from Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4.apply__O
[error]   called from Lorg_scalajs_testinterface_internal_Slave.org$scalajs$testinterface$internal$Slave$$jsonArg$1__F0__sjs_js_Dynamic
[error]   called from Lorg_scalajs_testinterface_internal_Slave.handleMsgImpl__T__F0__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.handleMsg__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$anonfun$1__p1__T__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init__V
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.$$js$exported$meth$init__O
[error]   called from Lorg_scalajs_testinterface_internal_BridgeBase.init
[error]   exported to JavaScript with @JSExport
[error] involving instantiated classes:
[error]   Lcom_wix_accord_tests_transform_ExpressionDescriberTests$$anonfun$2$$anonfun$apply$mcV$sp$4
[error]   Lorg_scalajs_testinterface_internal_Slave
[error]   Lorg_scalajs_testinterface_internal_Master
[trace] Stack trace suppressed: run last coreJS/test:scalaJSLinkingUnitClasspath for the full output.
[error] (coreJS/test:scalaJSLinkingUnitClasspath) There were linking errors
[error] Total time: 23 s, completed Jul 14, 2015 6:11:18 PM
```
If anyone has a clue, let me know; this is all the time I have for this today.

**Comment by holograph** [comment] 2015-07-14 15:35
Found some extra time and the problem is now fixed on the target branch! I need to do some reading about how to publish (and exemplify usage) of Scala.js artifacts, but we're damn near good to go. Looks like the 0.5 release is closer than I thought :-)

**Comment by holograph** [comment] 2015-07-19 07:31
This is currently blocked on scoverage/sbt-scoverage#101. If coverage can't be specifically disabled for Scala.js, this would either mean foregoing coverage tests entirely or else waiting 'till the issue is fixed.

**Comment by russwyte** [comment] 2015-07-20 15:47
@holograph 
Not sure if this will help but I work around the scala.js issue with scoverage by creating an alias that I use separately from the normal build. As long as I clean - before publishing things seem to do fine.

The alias only run the test on the JVM project of the crossbuild.

example:
addCommandAlias("testCoverage",";clean ;coverage ;fooJVM/test ;coverageReport")

**Closed** 2015-07-27 12:12 UTC
Labels: enhancement

**Comment by holograph** [comment] 2015-07-27 21:19
@russwyte It might help, but after dicking around with sbt for a few hours I honestly prefer to just disable coverage until the issue is fixed. I have my doubts about coverage numbers being useful to begin with...
